/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.au;

import org.apache.commons.cli.*;
import org.apache.commons.lang3.text.WordUtils;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws ParseException {
        //System.out.println(new App().getGreeting());
        Option msg = Option.builder("m")
                .longOpt("message")
                .hasArg()
                .desc("the message to capitalize")
                .build();
        Options options = new Options();
        options.addOption(msg);

        CommandLineParser parser = new DefaultParser();
        CommandLine line = parser.parse(options, args);

        String  message = line.getOptionValue("m", "Hello Ivy!");
        System.out.println("standard message : " + message);
        System.out.println("capitalized by " + WordUtils.class.getName()
                + " : " + WordUtils.capitalizeFully(message));
    }

    public static String commonsTest(String[] args) throws ParseException {
        Option msg = Option.builder("m")
                .longOpt("message")
                .hasArg()
                .desc("the message to capitalize")
                .build();
        Options options = new Options();
        options.addOption(msg);

        CommandLineParser parser = new DefaultParser();
        CommandLine line = parser.parse(options, args);

        String  message = line.getOptionValue("m", "Hello Ivy!");
//        System.out.println("standard message : " + message);
//        System.out.println("capitalized by " + WordUtils.class.getName()
//                + " : " + WordUtils.capitalizeFully(message));

        return WordUtils.capitalizeFully(message);
    }
}
